# The contents of this file is based on https://github.com/home-assistant/core/blob/dev/pyproject.toml

target-version = "py312"
exclude = ["./tests/_test*"]

[lint]
select = ["ALL"]

ignore = [
    "ARG001", # "unused-argument"
    "ANN401", # Dynamically typed expressions (typing.Any) are disallowed
    "D203", # no-blank-line-before-class (incompatible with formatter)
    "D212", # multi-line-summary-first-line (incompatible with formatter)
    "COM812", # incompatible with formatter

    # Temporary exceptions for Ruff implementation
    "PERF401", # manual-list-comprehension
    "EXE002",
    "PLR0912",
    "E501",
    "PLR0915",
    "ARG002",
    "BLE001",
    "TRY300",
    "FBT001",
    "PLR0911", # too many return statements
    "D102",    # missing docstring in public method
    "D107",    # missing docstring in __init__
]

[lint.flake8-pytest-style]
fixture-parentheses = false

[lint.pyupgrade]
keep-runtime-typing = true

[lint.mccabe]
max-complexity = 25

[lint.per-file-ignores]
"**/{tests,docs,tools}/*" = [
    "S101", # Use of assert
    "PLR2004", # Magic numbers
    "SLF001", # Private member accessed
]